In [4]:
import  tensorflow as tf
import  numpy as np

In [5]:
print('pacakage loaded')
print('current tf version is %s', (tf.__version__) )

pacakage loaded
current tf version is %s 1.3.0


In [6]:
sess = tf.Session()
print('OPEN SESSION')

OPEN SESSION


In [7]:
def print_tf(x) :
    print('TYPE IS\n %s' % (type(x)))
    print('Value is \n %s'  % (x))
    print('end')


In [8]:
hello = tf.constant("Hello, it's me.")
print_tf(hello)

hello_out = sess.run(hello)
print_tf(hello_out)


TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
Value is 
 Tensor("Const:0", shape=(), dtype=string)
end
TYPE IS
 <class 'bytes'>
Value is 
 b"Hello, it's me."
end


In [9]:
a = tf.constant(1.5)
b = tf.constant(2.5)
print_tf(a)
print_tf(b)


TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
Value is 
 Tensor("Const_1:0", shape=(), dtype=float32)
end
TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
Value is 
 Tensor("Const_2:0", shape=(), dtype=float32)
end


In [10]:
a_out = sess.run(a)
b_out = sess.run(b)
print_tf(a_out)
print_tf(b_out)


TYPE IS
 <class 'numpy.float32'>
Value is 
 1.5
end
TYPE IS
 <class 'numpy.float32'>
Value is 
 2.5
end


In [13]:
a_plus_b = tf.add(a,b)
a_plus_b_out = sess.run(a_plus_b)
print_tf(a_plus_b_out)


TYPE IS
 <class 'numpy.float32'>
Value is 
 4.0
end


In [12]:
a_mul_b = tf.multiply(a,b)
a_mul_b_out = sess.run(a_mul_b)
print_tf(a_mul_b_out)

TYPE IS
 <class 'numpy.float32'>
Value is 
 3.75
end


In [15]:

weight = tf.Variable(tf.random_normal([5,2], stddev=0.1))
print_tf(weight)

weight_out = sess.run(weight)
print_tf(weight_out)


TYPE IS
 <class 'tensorflow.python.ops.variables.Variable'>
Value is 
 <tf.Variable 'Variable_1:0' shape=(5, 2) dtype=float32_ref>
end


FailedPreconditionError: Attempting to use uninitialized value Variable_1
	 [[Node: Variable_1/_10 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_4_Variable_1", _device="/job:localhost/replica:0/task:0/gpu:0"](Variable_1)]]
	 [[Node: Variable_1/_11 = _Recv[_start_time=0, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_4_Variable_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

In [16]:

init = tf.global_variables_initializer()
sess.run(init)


In [17]:
weight_out = sess.run(weight)
print_tf(weight_out)

TYPE IS
 <class 'numpy.ndarray'>
Value is 
 [[-0.08782052 -0.13036782]
 [ 0.12069062  0.13997839]
 [ 0.07874853  0.07181405]
 [ 0.03878408  0.01935917]
 [-0.03998749 -0.29000935]]
end


In [21]:
x = tf.placeholder(tf.float32, [None, 5]) #학습을 위한 입출력 데이터같은게 된다.
print_tf(x) 

TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
Value is 
 Tensor("Placeholder_1:0", shape=(?, 5), dtype=float32)
end


In [22]:
oper = tf.matmul(x, weight)
print_tf(oper)

TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
Value is 
 Tensor("MatMul:0", shape=(?, 2), dtype=float32)
end


In [30]:
data = np.random.rand(2,5)
print(data)
oper_out = sess.run(oper, feed_dict={x:data})
print_tf(oper_out)

[[ 0.55734678  0.36432494  0.0567335   0.54747971  0.92841265]
 [ 0.56298192  0.04448329  0.10240886  0.14284662  0.79484285]]
TYPE IS
 <class 'numpy.ndarray'>
Value is 
 [[-0.0163996  -0.27623782]
 [-0.06225169 -0.28756008]]
end
